<?php
namespace Training\UrlRewrite\Model;


class Generator
{
    private $urlRewriteFactory;

    private $storeManager;

    public function __construct(
        \Magento\UrlRewrite\Model\UrlRewriteFactory $urlRewriteFactory,
        \Magento\Store\Model\StoreManagerInterface $storeManager
    )
    {
        $this->urlRewriteFactory = $urlRewriteFactory;
        $this->storeManager = $storeManager;
    }

    public function generate($type)
    {
        $urlRewrite = $this->urlRewriteFactory->create();

        $items = ["page" => 1, "raw" => 2, "json" => 3, "redirect" => 4, "forward" => 5];

        $urlRewrite->setEntityType("custom")
            ->setEntityId($items[$type])
            ->setRequestPath("custom-page-" . $type . ".html")
            ->setTargetPath("action/type/" . $type)
            ->setRedirectType(0)
            ->setStoreId($this->storeManager->getStore()->getId())
            ->setIsAutoGenerated(1);

        $urlRewrite->save();
    }
}
